data_validation:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  schema_file: "src/schema.yaml"

data_splitting:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  train_file: "data/processed/train.csv"
  test_file: "data/processed/test.csv"
  target: "loan_status"
  test_size: 0.3

build_features:
  train_file: "data/processed/train.csv"
  target: "loan_status"
  artifacts_dir: "artifacts"
  transformer_file: "artifacts/woe_transformer.pickle"

train:
  train_file: "data/processed/train.csv"
  woe_transformer_params: {
    "numerical_columns": ["person_age", "person_income", "person_emp_length", "loan_amnt", "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"],
    "categorical_columns": ["person_home_ownership", "loan_intent", "loan_grade", "cb_person_default_on_file"],
    "bins": 5
  }
  logreg_params: {"random_state": 42}
  artifacts_dir: "artifacts"
  model_file: "artifacts/model.pickle"
  transformer_file: "artifacts/woe_transformer.pickle"
  target: "loan_status"
  test_file: "data/processed/test.csv"

evaluate:
  test_file: "data/processed/test.csv"
  model_file: "artifacts/model.pickle"
  target: "loan_status"

predict:
  artifacts_dir: "artifacts"
  model_file: "artifacts/model.pickle"
  transformer_file: "artifacts/woe_transformer.pickle"
  target: "loan_status"
  test_file: "data/processed/test.csv"