data_validation:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  schema_file: "src/schema.yaml"

data_splitting:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  train_file: "data/processed/train.csv"
  test_file: "data/processed/test.csv"
  target: "loan_status"
  test_size: 0.3

train:
  train_file: "data/processed/train.csv"
  woe_transformer_params: {
    "numerical_columns": ["person_age", "person_income", "person_emp_length", "loan_amnt", "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"],
    "categorical_columns": ["person_home_ownership", "loan_intent", "loan_grade", "cb_person_default_on_file"],
    "bins": 5
  }
  logreg_params: {"random_state": 42}
  model_file: "models/woe_lr.pickle"
  target: "loan_status"
  test_file: "data/processed/test.csv"
  calibration_curve_file: "reports/figures/train_calibration_curve.png"

evaluate:
  test_file: "data/processed/test.csv"
  model_file: "models/woe_lr.pickle"
  target: "loan_status"
  calibration_curve_file: "reports/figures/test_calibration_curve.png"

predict:
  model_file: "models/woe_lr.pickle"