person_age                 : int64  
person_income              : int64  
person_home_ownership      : object 
person_emp_length          : float64
loan_intent                : object 
loan_grade                 : object 
loan_amnt                  : int64  
loan_int_rate              : float64
loan_status                : int64  
loan_percent_income        : float64
cb_person_default_on_file  : object 
cb_person_cred_hist_length : int64  