data_validation:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  schema_file: "src/schema.yaml"

data_splitting:
  raw_data_file: "data/raw/credit_risk_dataset.csv"
  train_file: "data/interim/train.csv"
  test_file: "data/interim/test.csv"
  target: "loan_status"
  test_size: 0.3
  random_state: 42

build_features:
  train_file: "data/interim/train.csv"
  target: "loan_status"
  processed_train_file: "data/processed/train.csv"
  artifacts_dir: "artifacts"
  transformer_file: "artifacts/woe_transformer.pickle"

train:
  processed_train_file: "data/processed/train.csv"
  model_params: {"random_state": 42}
  artifacts_dir: "artifacts"
  model_file: "artifacts/model.pickle"
  transformer_file: "artifacts/woe_transformer.pickle"
  target: "loan_status"
  test_file: "data/interim/test.csv"

predict:
  artifacts_dir: "artifacts"
  model_file: "artifacts/model.pickle"
  transformer_file: "artifacts/woe_transformer.pickle"
  target: "loan_status"
  test_file: "data/interim/test.csv"